data "amazon-ami" "autogenerated_1" {
  filters = {
    name                = "ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["099720109477"]
  region      = "us-east-1"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "amazon-ebs" "autogenerated_1" {
  ami_description         = "Base image for headless ghost CMS system"
  ami_groups              = ["all"]
  ami_name                = "daringway-ghost-${local.timestamp}"
  ami_regions             = ["us-east-1"]
  ami_virtualization_type = "hvm"
  force_delete_snapshot   = "true"
  force_deregister        = "true"
  instance_type           = "t3.micro"
  region                  = "us-east-1"
  source_ami              = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username            = "ubuntu"
  tags = {
    Application         = "ghost"
    Base_AMI_Name       = "{{ .SourceAMIName }}"
    DISTRIB_CODENAME    = "bionic"
    DISTRIB_DESCRIPTION = "Ubuntu 18.04.4 LTS"
    DISTRIB_ID          = "Ubuntu"
    DISTRIB_RELEASE     = "18.04"
    OS_CODENAME         = "bionic"
    OS_Name             = "Ubuntu"
    OS_Version          = "18.04"
    SSHUSER             = "ubuntu"
  }
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "file" {
    destination = "/tmp"
    source      = "templates"
  }

  provisioner "shell" {
    script = "./provision.sh"
  }

}
